name: ccc-dev
channels:
- conda-forge
dependencies:
- python>3.10, <3.14
- pandas
- numba
- paramtools>=0.20.0
- bokeh
- setuptools
- pip
- xlrd
- openpyxl
- pytest
- pytest-xdist
- pycodestyle
- pylint
- coverage
- black
- pip:
  - taxcalc>=5.2.0
  - jupyter-book
  - "cs-kit>=1.16.8"
  - cs2tc
