name: ccc-dev
channels:
- conda-forge
dependencies:
- python
- "taxcalc>=3.1.0"
- "paramtools>=0.14.2"
- "bokeh>=1.4.0"
- setuptools
- pip
- xlrd
- openpyxl
- pytest
- pytest-xdist
- pycodestyle
- pylint
- coverage
- pip:
  - jupyter-book>=0.9.1
  - cs-kit
  - cs2tc
