name: btax-dev
channels:
- ospc
dependencies:
- taxcalc>=0.22.0
- numpy >=1.12.1
- pandas >=0.23.4
- numba
- toolz
- six
- bokeh >=0.12.3
- mock
- pep8
- pylint
- coverage
- pytest-pep8
- pytest-xdist
- xlrd
