

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ source_url }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - setuptools
    - python

  run:
    - setuptools
    - scipy
    - taxcalc
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - python
    - pytest
    - xlrd

about:
  home: https://github.com/open-source-economics/B-Tax/
  summary: B-Tax is a model used to evaluate the effect of taxation on investment incentives.

extra:
  maintainers:
   - Jason Debacker
   - Peter Steinberg
