
# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "btax" %}
{% set repo_name = "B-Tax" %}
{% set git_org = "PeterDSteinberg" %}
{% set version = "0.1.091" %}
{% set sha256 = "d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f" %}
# sha256 is the prefered checksum -- you can get it for a file with:
#  `openssl sha256 <file name>`.
# You may need the openssl package, available on conda-forge
#  `conda install openssl -c conda-forge``

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ git_org }}/{{ repo_name }}/archive/{{ repo_name }}-{{ version }}.tar.gz
  script: python setup.py install --single-version-externally-managed --record record.txt

build:
  number: 0

requirements:
  build:
    - setuptools
    - scipy
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - python ==2.7
    - pytest
    - xlrd

  run:
    - setuptools
    - scipy
    - taxcalc
    - matplotlib
    - numpy
    - pandas ==0.18.1
    - python ==2.7
    - pytest
    - xlrd

about:
  home: https://github.com/open-source-economics/B-Tax/
